version: '3'
services:
#mssql docker
  erecipes-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest #server
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ismi123!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - erecipes2


  rabbitmq:
    image: rabbitmq:3.12.1-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
    networks:
      - erecipes2

  
  erecipes-rabbitmq:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.notifications
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=mypass
      - RABBITMQ_VIRTUALHOST=/
    depends_on:
      - rabbitmq
      - erecipes-sql
      - erecipes-api
    networks:
      - erecipes2
    ports:
      - 7111:80

  erecipes-api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile 
    environment:
      - ConnectionStrings__DefaultConnection=Server=erecipes-sql,1433;Database=eRecipes3;User=sa;Password=ismi123!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5089:5089
    networks:
      - erecipes2
    depends_on:
      - erecipes-sql
      
networks:
  erecipes2:
    driver: bridge      