// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eRecipes.Service.Database;

#nullable disable

namespace eRecipes.Service.Migrations
{
    [DbContext(typeof(ERecipesContext))]
    [Migration("20250117123559_addAtribute")]
    partial class addAtribute
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eRecipes.Service.Database.Izvjestaj", b =>
                {
                    b.Property<int>("IzvjestajId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IzvjestajId"));

                    b.Property<int?>("BrojKupovina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("BrojLajkova")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("BrojPregleda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateOnly>("DatumIzvjestaja")
                        .HasColumnType("date");

                    b.Property<int?>("ReceptId")
                        .HasColumnType("int");

                    b.HasKey("IzvjestajId")
                        .HasName("PK__Izvjesta__0892A342115805A3");

                    b.HasIndex("ReceptId");

                    b.ToTable("Izvjestaj", (string)null);
                });

            modelBuilder.Entity("eRecipes.Service.Database.Kategorija", b =>
                {
                    b.Property<int>("KategorijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategorijaId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("KategorijaId")
                        .HasName("PK__Kategori__6C3B8FEE5DB06CF5");

                    b.ToTable("Kategorija", (string)null);
                });

            modelBuilder.Entity("eRecipes.Service.Database.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikId"));

                    b.Property<DateTime?>("DatumRodjenja")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("KorisnikId")
                        .HasName("PK__Korisnik__80B06D412AF902FE");

                    b.HasIndex("UlogaId");

                    b.ToTable("Korisnik", (string)null);
                });

            modelBuilder.Entity("eRecipes.Service.Database.Lajkovi", b =>
                {
                    b.Property<int>("LajkoviId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LajkoviId"));

                    b.Property<DateTime?>("DatumLajka")
                        .HasColumnType("datetime");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceptId")
                        .HasColumnType("int");

                    b.HasKey("LajkoviId")
                        .HasName("PK__Lajkovi__3D31B5F953B26C49");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ReceptId");

                    b.ToTable("Lajkovi", (string)null);
                });

            modelBuilder.Entity("eRecipes.Service.Database.Obavijest", b =>
                {
                    b.Property<int>("ObavijestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObavijestId"));

                    b.Property<DateOnly>("DatumSlanja")
                        .HasColumnType("date");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ObavijestId")
                        .HasName("PK__Obavijes__99D330E0EA8A25AD");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Obavijest", (string)null);
                });

            modelBuilder.Entity("eRecipes.Service.Database.OmiljeniRecept", b =>
                {
                    b.Property<int>("OmiljeniReceptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OmiljeniReceptId"));

                    b.Property<DateTime?>("DatumDodavanja")
                        .HasColumnType("datetime");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceptId")
                        .HasColumnType("int");

                    b.HasKey("OmiljeniReceptId")
                        .HasName("PK__Omiljeni__1A663C0CF03DFE09");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ReceptId");

                    b.ToTable("OmiljeniRecept", (string)null);
                });

            modelBuilder.Entity("eRecipes.Service.Database.Recept", b =>
                {
                    b.Property<int>("ReceptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceptId"));

                    b.Property<DateTime?>("DatumObjave")
                        .HasColumnType("datetime");

                    b.Property<int?>("KategorijaId")
                        .HasColumnType("int");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisPripreme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisRecepta")
                        .HasColumnType("text");

                    b.Property<bool?>("Premium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("StateMachine")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("VrijemePripreme")
                        .HasColumnType("int");

                    b.Property<int?>("VrstaJelaId")
                        .HasColumnType("int");

                    b.HasKey("ReceptId")
                        .HasName("PK__Recept__AFE1E3C322D7424C");

                    b.HasIndex("KategorijaId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("VrstaJelaId");

                    b.ToTable("Recept", (string)null);
                });

            modelBuilder.Entity("eRecipes.Service.Database.ReceptSastojak", b =>
                {
                    b.Property<int>("ReceptSastojakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceptSastojakId"));

                    b.Property<decimal?>("Kolicina")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("MjernaJedinica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReceptId")
                        .HasColumnType("int");

                    b.Property<int?>("SastojakId")
                        .HasColumnType("int");

                    b.HasKey("ReceptSastojakId")
                        .HasName("PK__ReceptSa__865053CEFA1A8ED2");

                    b.HasIndex("ReceptId");

                    b.HasIndex("SastojakId");

                    b.ToTable("ReceptSastojak", (string)null);
                });

            modelBuilder.Entity("eRecipes.Service.Database.Sastojak", b =>
                {
                    b.Property<int>("SastojakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SastojakId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SastojakId")
                        .HasName("PK__Sastojak__114FC27F5EBEDC87");

                    b.ToTable("Sastojak", (string)null);
                });

            modelBuilder.Entity("eRecipes.Service.Database.Uloga", b =>
                {
                    b.Property<int>("UlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UlogaId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UlogaId")
                        .HasName("PK__Uloga__DCAB23CBCE26A230");

                    b.ToTable("Uloga", (string)null);
                });

            modelBuilder.Entity("eRecipes.Service.Database.VrstaJela", b =>
                {
                    b.Property<int>("VrstaJelaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VrstaJelaId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VrstaJelaId")
                        .HasName("PK__VrstaJel__E76FF56D8812CE35");

                    b.ToTable("VrstaJela", (string)null);
                });

            modelBuilder.Entity("eRecipes.Service.Database.Izvjestaj", b =>
                {
                    b.HasOne("eRecipes.Service.Database.Recept", "Recept")
                        .WithMany("Izvjestajs")
                        .HasForeignKey("ReceptId")
                        .HasConstraintName("FK__Izvjestaj__Recep__5BE2A6F2");

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Korisnik", b =>
                {
                    b.HasOne("eRecipes.Service.Database.Uloga", "Uloga")
                        .WithMany("Korisnik")
                        .HasForeignKey("UlogaId")
                        .HasConstraintName("FK__Korisnik__Uloga__440B1D66");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Lajkovi", b =>
                {
                    b.HasOne("eRecipes.Service.Database.Korisnik", "Korisnik")
                        .WithMany("Lajkovis")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__Lajkovi__Korisni__4CA06362");

                    b.HasOne("eRecipes.Service.Database.Recept", "Recept")
                        .WithMany("Lajkovis")
                        .HasForeignKey("ReceptId")
                        .HasConstraintName("FK__Lajkovi__ReceptI__4D94879B");

                    b.Navigation("Korisnik");

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Obavijest", b =>
                {
                    b.HasOne("eRecipes.Service.Database.Korisnik", "Korisnik")
                        .WithMany("Obavijests")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__Obavijest__Koris__5629CD9C");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eRecipes.Service.Database.OmiljeniRecept", b =>
                {
                    b.HasOne("eRecipes.Service.Database.Korisnik", "Korisnik")
                        .WithMany("OmiljeniRecepts")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__OmiljeniR__Koris__48CFD27E");

                    b.HasOne("eRecipes.Service.Database.Recept", "Recept")
                        .WithMany("OmiljeniRecepts")
                        .HasForeignKey("ReceptId")
                        .HasConstraintName("FK__OmiljeniR__Recep__49C3F6B7");

                    b.Navigation("Korisnik");

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Recept", b =>
                {
                    b.HasOne("eRecipes.Service.Database.Kategorija", "Kategorija")
                        .WithMany("Recepts")
                        .HasForeignKey("KategorijaId")
                        .HasConstraintName("FK__Recept__Kategori__45F365D3");

                    b.HasOne("eRecipes.Service.Database.Korisnik", "Korisnik")
                        .WithMany("Recepts")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__Recept__Korisnik__440B1D61");

                    b.HasOne("eRecipes.Service.Database.VrstaJela", "VrstaJela")
                        .WithMany("Recepts")
                        .HasForeignKey("VrstaJelaId")
                        .HasConstraintName("FK__Recept__VrstaJel__44FF419A");

                    b.Navigation("Kategorija");

                    b.Navigation("Korisnik");

                    b.Navigation("VrstaJela");
                });

            modelBuilder.Entity("eRecipes.Service.Database.ReceptSastojak", b =>
                {
                    b.HasOne("eRecipes.Service.Database.Recept", "Recept")
                        .WithMany("ReceptSastojaks")
                        .HasForeignKey("ReceptId")
                        .HasConstraintName("FK__ReceptSas__Recep__52593CB8");

                    b.HasOne("eRecipes.Service.Database.Sastojak", "Sastojak")
                        .WithMany("ReceptSastojaks")
                        .HasForeignKey("SastojakId")
                        .HasConstraintName("FK__ReceptSas__Sasto__534D60F1");

                    b.Navigation("Recept");

                    b.Navigation("Sastojak");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Kategorija", b =>
                {
                    b.Navigation("Recepts");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Korisnik", b =>
                {
                    b.Navigation("Lajkovis");

                    b.Navigation("Obavijests");

                    b.Navigation("OmiljeniRecepts");

                    b.Navigation("Recepts");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Recept", b =>
                {
                    b.Navigation("Izvjestajs");

                    b.Navigation("Lajkovis");

                    b.Navigation("OmiljeniRecepts");

                    b.Navigation("ReceptSastojaks");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Sastojak", b =>
                {
                    b.Navigation("ReceptSastojaks");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Uloga", b =>
                {
                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eRecipes.Service.Database.VrstaJela", b =>
                {
                    b.Navigation("Recepts");
                });
#pragma warning restore 612, 618
        }
    }
}
