// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eRecipes.Service.Database;

#nullable disable

namespace eRecipes.Service.Migrations
{
    [DbContext(typeof(ERecipesContext))]
    [Migration("20250123195935_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eRecipes.Service.Database.Izvjestaj", b =>
                {
                    b.Property<int>("IzvjestajId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IzvjestajId"));

                    b.Property<int>("BrojKupovina")
                        .HasColumnType("int");

                    b.Property<int>("BrojLajkova")
                        .HasColumnType("int");

                    b.Property<int>("BrojPregleda")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumIzvjestaja")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.HasKey("IzvjestajId");

                    b.HasIndex("ReceptId");

                    b.ToTable("Izvjestajs");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Kategorija", b =>
                {
                    b.Property<int>("KategorijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategorijaId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("KategorijaId");

                    b.ToTable("Kategorijas");

                    b.HasData(
                        new
                        {
                            KategorijaId = 1,
                            Naziv = "Predjelo",
                            Status = true
                        },
                        new
                        {
                            KategorijaId = 2,
                            Naziv = "Glavno jelo",
                            Status = true
                        },
                        new
                        {
                            KategorijaId = 3,
                            Naziv = "Desert",
                            Status = true
                        });
                });

            modelBuilder.Entity("eRecipes.Service.Database.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikId"));

                    b.Property<DateTime?>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("KorisnikId");

                    b.HasIndex("UlogaId");

                    b.ToTable("Korisniks");

                    b.HasData(
                        new
                        {
                            KorisnikId = 1,
                            DatumRodjenja = new DateTime(1995, 1, 23, 20, 59, 35, 262, DateTimeKind.Local).AddTicks(7303),
                            Email = "admin@mail.com",
                            Ime = "Admin",
                            KorisnickoIme = "admin",
                            LozinkaHash = "tPW/IOLa2TZIKYSA50IDeaJKYtg=",
                            LozinkaSalt = "2G2wAwYkdFgpMleomcwelg==",
                            Prezime = "Adminovic",
                            Status = true,
                            Telefon = "060-000-000",
                            UlogaId = 1
                        },
                        new
                        {
                            KorisnikId = 2,
                            DatumRodjenja = new DateTime(2002, 1, 23, 20, 59, 35, 262, DateTimeKind.Local).AddTicks(7393),
                            Email = "korisnik@mail.com",
                            Ime = "Korisnik",
                            KorisnickoIme = "korisnik",
                            LozinkaHash = "tPW/IOLa2TZIKYSA50IDeaJKYtg=",
                            LozinkaSalt = "2G2wAwYkdFgpMleomcwelg==",
                            Prezime = "Korisnikovic",
                            Status = true,
                            Telefon = "060-000-001",
                            UlogaId = 2
                        },
                        new
                        {
                            KorisnikId = 3,
                            DatumRodjenja = new DateTime(1980, 1, 23, 20, 59, 35, 262, DateTimeKind.Local).AddTicks(7397),
                            Email = "bajaspare@mail.com",
                            Ime = "Baja",
                            KorisnickoIme = "premium",
                            LozinkaHash = "tPW/IOLa2TZIKYSA50IDeaJKYtg=",
                            LozinkaSalt = "2G2wAwYkdFgpMleomcwelg==",
                            Prezime = "Bajaspare",
                            Status = true,
                            Telefon = "060-000-002",
                            UlogaId = 3
                        });
                });

            modelBuilder.Entity("eRecipes.Service.Database.Lajkovi", b =>
                {
                    b.Property<int>("LajkoviId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LajkoviId"));

                    b.Property<DateTime>("DatumLajka")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.HasKey("LajkoviId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ReceptId");

                    b.ToTable("Lajkovis");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Obavijest", b =>
                {
                    b.Property<int>("ObavijestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObavijestId"));

                    b.Property<DateTime>("DatumSlanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObavijestId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Obavijests");
                });

            modelBuilder.Entity("eRecipes.Service.Database.OmiljeniRecept", b =>
                {
                    b.Property<int>("OmiljeniReceptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OmiljeniReceptId"));

                    b.Property<DateTime>("DatumDodavanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.HasKey("OmiljeniReceptId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ReceptId");

                    b.ToTable("OmiljeniRecepts");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Recept", b =>
                {
                    b.Property<int>("ReceptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceptId"));

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<int>("KategorijaId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisPripreme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisRecepta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Premium")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("VrijemePripreme")
                        .HasColumnType("int");

                    b.Property<int>("VrstaJelaId")
                        .HasColumnType("int");

                    b.HasKey("ReceptId");

                    b.HasIndex("KategorijaId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("VrstaJelaId");

                    b.ToTable("Recepts");
                });

            modelBuilder.Entity("eRecipes.Service.Database.ReceptSastojak", b =>
                {
                    b.Property<int>("ReceptSastojakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceptSastojakId"));

                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.Property<int>("SastojakId")
                        .HasColumnType("int");

                    b.HasKey("ReceptSastojakId");

                    b.HasIndex("ReceptId");

                    b.HasIndex("SastojakId");

                    b.ToTable("ReceptSastojaks");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Sastojak", b =>
                {
                    b.Property<int>("SastojakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SastojakId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SastojakId");

                    b.ToTable("Sastojaks");

                    b.HasData(
                        new
                        {
                            SastojakId = 1,
                            Naziv = "Jaje"
                        },
                        new
                        {
                            SastojakId = 2,
                            Naziv = "Brašno"
                        },
                        new
                        {
                            SastojakId = 3,
                            Naziv = "Šećer"
                        },
                        new
                        {
                            SastojakId = 4,
                            Naziv = "Mlijeko"
                        },
                        new
                        {
                            SastojakId = 5,
                            Naziv = "Maslac"
                        },
                        new
                        {
                            SastojakId = 6,
                            Naziv = "So"
                        },
                        new
                        {
                            SastojakId = 7,
                            Naziv = "Prašak za pecivo"
                        },
                        new
                        {
                            SastojakId = 8,
                            Naziv = "Čokolada"
                        },
                        new
                        {
                            SastojakId = 9,
                            Naziv = "Vanilin šećer"
                        },
                        new
                        {
                            SastojakId = 10,
                            Naziv = "Maslinovo ulje"
                        });
                });

            modelBuilder.Entity("eRecipes.Service.Database.Uloga", b =>
                {
                    b.Property<int>("UlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UlogaId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UlogaId");

                    b.ToTable("Ulogas");

                    b.HasData(
                        new
                        {
                            UlogaId = 1,
                            Naziv = "Admin",
                            Opis = "Ovaj moze sta god hoce :D"
                        },
                        new
                        {
                            UlogaId = 2,
                            Naziv = "Korisnik",
                            Opis = "Ovaj je obican smrtnik"
                        },
                        new
                        {
                            UlogaId = 3,
                            Naziv = "Premium korisnik",
                            Opis = "Ovaj baja imama para"
                        });
                });

            modelBuilder.Entity("eRecipes.Service.Database.VrstaJela", b =>
                {
                    b.Property<int>("VrstaJelaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VrstaJelaId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VrstaJelaId");

                    b.ToTable("VrstaJelas");

                    b.HasData(
                        new
                        {
                            VrstaJelaId = 4,
                            Naziv = "Kolač"
                        },
                        new
                        {
                            VrstaJelaId = 5,
                            Naziv = "Juha"
                        },
                        new
                        {
                            VrstaJelaId = 6,
                            Naziv = "Salata"
                        },
                        new
                        {
                            VrstaJelaId = 7,
                            Naziv = "Tjestenina"
                        },
                        new
                        {
                            VrstaJelaId = 8,
                            Naziv = "Pizza"
                        },
                        new
                        {
                            VrstaJelaId = 9,
                            Naziv = "Sendvič"
                        },
                        new
                        {
                            VrstaJelaId = 10,
                            Naziv = "Zdravi obrok"
                        });
                });

            modelBuilder.Entity("eRecipes.Service.Database.Izvjestaj", b =>
                {
                    b.HasOne("eRecipes.Service.Database.Recept", "Recept")
                        .WithMany("Izvjestajs")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Korisnik", b =>
                {
                    b.HasOne("eRecipes.Service.Database.Uloga", "Uloga")
                        .WithMany("Korisnik")
                        .HasForeignKey("UlogaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Lajkovi", b =>
                {
                    b.HasOne("eRecipes.Service.Database.Korisnik", "Korisnik")
                        .WithMany("Lajkovis")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eRecipes.Service.Database.Recept", "Recept")
                        .WithMany("Lajkovis")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Obavijest", b =>
                {
                    b.HasOne("eRecipes.Service.Database.Korisnik", "Korisnik")
                        .WithMany("Obavijests")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eRecipes.Service.Database.OmiljeniRecept", b =>
                {
                    b.HasOne("eRecipes.Service.Database.Korisnik", "Korisnik")
                        .WithMany("OmiljeniRecepts")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eRecipes.Service.Database.Recept", "Recept")
                        .WithMany("OmiljeniRecepts")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Recept", b =>
                {
                    b.HasOne("eRecipes.Service.Database.Kategorija", "Kategorija")
                        .WithMany("Recepts")
                        .HasForeignKey("KategorijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eRecipes.Service.Database.Korisnik", "Korisnik")
                        .WithMany("Recepts")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eRecipes.Service.Database.VrstaJela", "VrstaJela")
                        .WithMany("Recepts")
                        .HasForeignKey("VrstaJelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorija");

                    b.Navigation("Korisnik");

                    b.Navigation("VrstaJela");
                });

            modelBuilder.Entity("eRecipes.Service.Database.ReceptSastojak", b =>
                {
                    b.HasOne("eRecipes.Service.Database.Recept", "Recept")
                        .WithMany("ReceptSastojaks")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eRecipes.Service.Database.Sastojak", "Sastojak")
                        .WithMany("ReceptSastojaks")
                        .HasForeignKey("SastojakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recept");

                    b.Navigation("Sastojak");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Kategorija", b =>
                {
                    b.Navigation("Recepts");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Korisnik", b =>
                {
                    b.Navigation("Lajkovis");

                    b.Navigation("Obavijests");

                    b.Navigation("OmiljeniRecepts");

                    b.Navigation("Recepts");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Recept", b =>
                {
                    b.Navigation("Izvjestajs");

                    b.Navigation("Lajkovis");

                    b.Navigation("OmiljeniRecepts");

                    b.Navigation("ReceptSastojaks");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Sastojak", b =>
                {
                    b.Navigation("ReceptSastojaks");
                });

            modelBuilder.Entity("eRecipes.Service.Database.Uloga", b =>
                {
                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eRecipes.Service.Database.VrstaJela", b =>
                {
                    b.Navigation("Recepts");
                });
#pragma warning restore 612, 618
        }
    }
}
